=== BigRedDoge/msaf/jams2/jams_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "definitions": {
        
        "annotation_metadata": {
            "type": "object",
            "title": "Annotation metadata",
            "description": "All metadata required to describe an annotation",
            "properties": {
                "attribute": { "type": "string"},
                "corpus": { "type": "string" },
                "version": { "type": "number", "minimum": 0},
                "annotator": { 
                    "type": "object",
                    "title": "Annotator",
                    "description": "Annotator name and email",
                    "properties": {
                        "name": { "type": "string"},
                        "email": { "type": "string", "format": "email" }
                    }
                },
                "annotation_tools": { "type": "string"},
                "annotation_rules": { "type": "string"},
                "validation_and_reliability": { "type": "string"},
                "origin": { "type": "string"}
            }
        },

        "observation": {
            "type": "object",
            "title": "Observation",
            "description": "An observation with a single value and confidence, e.g. a time, a frequency value, or a chord label",
            "properties": {
                "value": { "type": ["number","string","boolean"] },
                "confidence": { "type": "number" }
            }
        },

        "event": {
            "type": "object",
            "title": "Event",
            "description": "An event that occurs in a single point in time, e.g. an onset",
            "properties": {
                "time": { "$ref": "#/definitions/observation" },
                "label": { "$ref": "#/definitions/observation" }
            }
        },

        "range": {
            "type": "object",
            "title": "Range",
            "description": "A concept that spans a certain time range, e.g. a chord",
            "properties": {
                "start": { "$ref": "#/definitions/observation" },
                "end": { "$ref": "#/definitions/observation" },
                "label": { "$ref": "#/definitions/observation" }
            }
        },

        "time_series": {
            "type": "object",
            "title": "Time Series",
            "description": "A sequence of values with corresponding timestamps and confidence esitmates",
            "properties": {
                "label": { "type": "string" },
                "value": {
                    "type": "array",
                    "title": "Value",
                    "description": "The values of the time series",
                    "items": { "type": ["number","string","boolean"] }
                },
                "time": {
                    "type": "array",
                    "title": "Time",
                    "description": "The timestamps of the time series",
                    "items": { "type": "number" }
                },
                "confidence": {
                    "type": "array",
                    "title": "Confidence",
                    "description": "The per-value confidence of the time series",
                    "items": { "type": "number" }
                }
            }
        },

        "observation_annotation": {
            "type": "object",
            "title": "Observation Annotation",
            "description": "An annotation of a single observation, e.g. genre",
            "properties": {
                "data": { 
                    "type": "array",
                    "title": "Data",
                    "description": "An array of observations",
                    "items": { "$ref": "#/definitions/observation" }
                },
                "metadata": { "$ref": "#/definitions/annotation_metadata" }
            }
        },

        "event_annotation" : {
            "type": "object",
            "title": "Event Annotation",
            "description": "An annotation of events, e.g. beats, onsets",
            "properties": {
                "data": {
                    "type": "array",
                    "title": "Data",
                    "description": "An array of events",
                    "items": { "$ref": "#/definitions/event" }
                },
                "metadata": { "$ref": "#/definitions/annotation_metadata" }
            }
        },

        "range_annotation" : {
            "type": "object",
            "title": "Range Annotation",
            "description": "An annotation of ranges, e.g. chords, sections",
            "properties": {
                "data": {
                    "type": "array",
                    "title": "Data",
                    "description": "An array of ranges",
                    "items": { "$ref": "#/definitions/range" }
                },
                "metadata": { "$ref": "#/definitions/annotation_metadata" }
            }
        },

        "time_series_annotation" : {
            "type": "object",
            "title": "Time Series Annotation",
            "description": "An annotation of a time series, e.g. melody (f0)",
            "properties": {
                "data": { 
                    "type": "array",
                    "title": "Data",
                    "description": "An array of time series",
                    "items": { "$ref": "#/definitions/time_series" }
                },
                "metadata": { "$ref": "#/definitions/annotation_metadata" }
            }
        }
    },

    "type": "object",
    "title": "Audio Description",
    "description": "Human or computer generated audio annotations and meta data",
    "properties": {
        
        "version": { "type": "number" },
        
        "metadata": {
            "type": "object",
            "title": "Metadata",
            "properties": {
                "echonest_ID": { "type": "string", "pattern": "[A-Z]+[0-9]+"},
                "mbid": { "type": "string"},
                "artist": { "type": "string"},
                "title": { "type": "string"},
                "md5": { "type": "string", "pattern": "[a-fA-F0-9]{32}"},
                "duration": { "type": "string", "pattern": "[0-9][0-9]:[0-9][0-9]:[0-9][0-9]"}
            }
        },

        "genre": {
            "type": "array",
            "title": "Genre",
            "description": "Genre annotations",
            "items": { "$ref": "#/definitions/observation_annotation" }
        },

        "beats": {
            "type": "array",
            "title": "Beats",
            "description": "Beat annotations",
            "items": { "$ref": "#/definitions/event_annotation" }
        },

        "onsets": {
            "type": "array",
            "title": "Onsets",
            "description": "Onset annotations",
            "items": { "$ref": "#/definitions/event_annotation" }
        },

        "chords": {
            "type": "array",
            "title": "Chords",
            "description": "Chord annotations",
            "items": { "$ref": "#/definitions/range_annotation" }
        },

        "sections": {
            "type": "array",
            "title": "Sections",
            "description": "Section annotations",
            "items": { "$ref": "#/definitions/range_annotation" }
        },

        "notes": {
            "type": "array",
            "title": "Notes",
            "description": "Notes (symbolic) annotations",
            "items": { "$ref": "#/definitions/range_annotation" }
        },

        "melody": {
            "type": "array",
            "title": "Melody",
            "description": "Melody (continuous predominant f0) annotations",
            "items": { "$ref": "#/definitions/time_series_annotation" }
        },

        "pitch": {
            "type": "array",
            "title": "Pitch",
            "description": "Pitch (continuous f0) annotations",
            "items": { "$ref": "#/definitions/time_series_annotation" }
        },

        "patterns": {
            "type": "array",
            "title": "Patterns",
            "description": "Pattern annotations",
            "items": { "$ref": "#/definitions/time_series_annotation" }
        }
    }
}

=== BigRedDoge/msaf/jams2/ejh_example2.json
{
    "beats": [
        {
            "name": "something_memorable",
            "author": "ejhumphrey@nyu.edu",
            "group": "marl",
            "data": [
                {
                    "time": {
                        "value": 0.336689342,
                        "confidence": 1.0
                    },
                    "label": {
                        "value": 3,
                        "confidence": 1.0
                    }
                },
                {
                    "time": {
                        "value": 1.194807256,
                        "confidence": 1.0
                    },
                    "label": {
                        "value": 4,
                        "confidence": 1.0
                    }
                },
                {
                    "time": {
                        "value": 1.971995464,
                        "confidence": 1.0
                    },
                    "label": {
                        "value": 1,
                        "confidence": 1.0
                    }
                }
            ],
            "timestamp": "Fri Feb 14 10:03:30 2014"
        }
    ],
    "chords": [
        {
            "name": "something_memorable",
            "author": "tmc232@nyu.edu",
            "group": "marl",
            "data": [
                {
                    "start": {
                        "value": 0.0,
                        "confidence": 1.0
                    },
                    "end": {
                        "value": 3.091,
                        "confidence": 1.0
                    },
                    "label": {
                        "value": "N",
                        "confidence": 1.0
                    }
                },
                {
                    "start": {
                        "value": 3.091,
                        "confidence": 1.0
                    },
                    "end": {
                        "value": 3.918,
                        "confidence": 1.0
                    },
                    "label": {
                        "value": "D:min",
                        "confidence": 1.0
                    }
                },
                {
                    "start": {
                        "value": 3.918,
                        "confidence": 1.0
                    },
                    "end": {
                        "value": 4.941,
                        "confidence": 1.0
                    },
                    "label": {
                        "value": "Bb:maj",
                        "confidence": 1.0
                    }
                }
            ],
            "timestamp": "Fri Feb 14 10:11:03 2014"
        }
    ],
    "melody": [
        {
            "name": "something_memorable",
            "author": "justin.salamon@nyu.edu",
            "group": "marl-2",
            "data": [
                {
                    "value": [
                        272.5533807769767,
                        221.338953512844,
                        246.41061581293596,
                        237.26051326467623,
                        251.66279369149845,
                        262.2774372838999,
                        239.4817971016345,
                        256.60144462116006
                    ],
                    "time": [
                        0.12450575,
                        0.25808751,
                        0.36182483,
                        0.48671057,
                        0.5725176,
                        0.70828537,
                        0.82754226,
                        0.96508301
                    ],
                    "confidence": [
                        0.9588612590546348,
                        0.8821113997395683,
                        0.8375719986201495,
                        0.9083711844314711,
                        0.8637670482886021,
                        0.9252344518531272,
                        0.83558739038859,
                        0.8854623259345453
                    ]
                }
            ],
            "timestamp": "Fri Feb 14 10:23:37 2014"
        }
    ],
    "sections": [
        {
            "name": "something_memorable",
            "author": "oriol@nyu.edu",
            "group": "marl",
            "data": [
                {
                    "start": {
                        "value": 0.0,
                        "confidence": 1.0
                    },
                    "end": {
                        "value": 17.025,
                        "confidence": 1.0
                    },
                    "label": {
                        "value": "Intro",
                        "confidence": 1.0
                    }
                },
                {
                    "start": {
                        "value": 17.025,
                        "confidence": 1.0
                    },
                    "end": {
                        "value": 33.54,
                        "confidence": 1.0
                    },
                    "label": {
                        "value": "VerseA",
                        "confidence": 1.0
                    }
                },
                {
                    "start": {
                        "value": 33.54,
                        "confidence": 1.0
                    },
                    "end": {
                        "value": 52.871,
                        "confidence": 1.0
                    },
                    "label": {
                        "value": "Chorus",
                        "confidence": 1.0
                    }
                }
            ],
            "timestamp": "Fri Feb 14 10:11:03 2014"
        }
    ],
    "metadata": {
        "enid": "TR01924500",
        "mbid": "4d4221a4-1c00-4ad3-9f7c-e0457623bad0",
        "artist": "Michael Jackson",
        "title": "Beat It",
        "md5": "63e5ee0470e210d88e7af816a03d2086",
        "duration": "00:04:19",
        "version": "0.1"
    }
}
